# Метод имитации отжига

![](pandas.jpg)

In [1]:
import numpy as np 
import random as rnd

In [2]:
def queens(N):
    ver = np.arange(1, N + 1)
    hor = np.arange(1, N + 1)
    np.random.shuffle(hor)
    return np.column_stack((ver, hor)) # получаем массив
    # размерности (N, 2), отождествляющий расположение ферзей

In [3]:
matrix = queens(8) 
matrix

array([[1, 4],
       [2, 2],
       [3, 3],
       [4, 1],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8]])

In [4]:
def F(Q, N): # Q означает расположение ферзей 
    cnt = 0
    for i in range(N):
        for j in range(i + 1, N):
            if abs(Q[i, 0] - Q[j, 0]) == abs(Q[i, 1] - Q[j, 1]): 
                cnt += 1
    return cnt * 2 # учитываем взаимные атаки

In [5]:
F(matrix , 8)

32

In [6]:
def G(Q, N):
    a = np.delete(matrix, 0, 1).reshape(N) # преобразуем в одномерный массив
    while True:
        i = np.random.choice(a)
        j = np.random.choice(a)
        if i != j:
            break
        
    k = Q[i - 1, 1]
    Q[i - 1, 1] = Q[j - 1, 1]
    Q[j - 1, 1] = k
    return Q # получаем новое расположение ферзей

In [7]:
G(matrix , 8)

array([[1, 4],
       [2, 2],
       [3, 3],
       [4, 8],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 1]])

In [8]:
def simulated_annealing(Q, N, T, alpha):
    x_i = Q.copy() # сохраняем расположение ферзей для x_i 
    while True:
        T = alpha * T # понижаем температуру
        x_hat = G(Q, N) # массив Q теперь содержет расположение  ферзей с попракой на x_hat
        delta = F(x_hat, N) - F(x_i, N)
    
        if F(x_hat , N) == 0: 
            return x_hat
        elif delta < 0: 
            x_i = x_hat
        else:
            prob = np.exp(- delta / T) 
            if prob > rnd.random():
                x_i = x_hat

In [9]:
simulated_annealing(matrix, 8, 100, 0.95)

array([[1, 7],
       [2, 1],
       [3, 3],
       [4, 8],
       [5, 6],
       [6, 4],
       [7, 2],
       [8, 5]])